id: '7e1fe210-91ce-46e1-309a-08dc95fa43f7'
version: 'v1.4'
name: 'mssql_dv_and_mart'
description: 'mssql_dv_and_mart'
configuration:
  id: 'biGENIUS.Implementation.Generator.VaultAndMart.Mssql'
  version: '1.6.1'
sourceSystems:
  - id: '89e2a172-44a1-40d5-b03c-09ab1be79f21'
    name: 'pos'
    description: ''
    sourceSystemTypeId: 'f69491d8-eed8-43a0-89f9-60195b3415c2'
